---
- hosts: all
  gather_facts: true
  become: yes
  tasks:
  - name: ping
    action: ping

  - name: james18
    user:
      name: semaphore
      shell: /bin/bash

  - name: Touch a file
    copy:
      src: ./authorized_keys
      dest: /home/semaphore/.ssh/authorized_keys
      owner: semaphore
      group: semaphore
      mode: 400
