---
- hosts: all
  gather_facts: true
  become: yes
  tasks:
  - name: ping
    action: ping

  - name: james18
    user:
      name: semaphore
      password: "{{ 'Admin@123' | password_hash('sha512') }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      shell: /bin/bash

  - name: Touch a file
    copy:
      src: ./authorized_keys
      dest: /home/semaphore/.ssh/authorized_keys
      owner: semaphore
      group: semaphore
      mode: 400
