---
- name: "Inital Connection Iesting"
  debug:
    msg: "OS {{ ansible_distribution }} Kernel {{ ansible_distribution_version }}"  

- name: Execute the Uptime 
  command: "uptime"
  register: uptimeoutput

- debug:
    msg: "{{ uptimeoutput.stdout_lines }}"
