---
- name: "Inital Connection Iesting"
  debug:
    msg: "OS {{ ansible_distribution }} Kernel {{ ansible_distribution_version }}"  

- name: Execute the Uptime 
  shell: "uptime"
  register: upout

- debug:
    msg: "{{ upout }}"

