---
- name: "Inital Connection Iesting"
  debug:
    msg: "OS {{ ansible_distribution }} Kernel {{ ansible_distribution_version }}"  

- name: Execute the Uptime 
  command: "uptime"
  register: regis2

- debug:
    msg: "{{ regis }} {{ regis2.out }}"

