---
- name: "Inital Connection Iesting"
  debug:
    msg: "OS {{ ansible_distribution }} Kernel {{ ansible_kernel }}"  

- name: Execute the Uptime 
  shell: "uptime"
  register: upout

- debug:
    msg: "{{ upout.stdout_lines }}"

- name: TOP Command
  shell: top -d 5 -b -o %MEM | head -n 15
  register: topout

- debug:
    msg: "{{ topout.stdout_lines }}"
