---
- name: "[1] User variables in ROLES"
  debug:
    msg: "this it the first message {{ MESSAGE }} for {{ ENV }}"  

- name: "[2a] Create a file based on ENV"
  debug:
    msg:  "this it the first message {{ MESSAGE }} for {{ ENV }}"  

- name: "[3] ls the files"
  shell:
    ls -l /tmp
  register: touch_out
  delegate_to: localhost

- debug:
    msg: "{{ touch_out.stdout_lines }}"

- name: "--- [4] When ENV == Prod ---"
  debug:
    msg: "Sample three when ENV={{ ENV }} matches prod {{ MESSAGE }}"
  when: ENV == "Prod"
